### ISSUE TITLE
谷歌推送失败

### ISSUE THREAD

**Issue by suyin-long** [cjh0613/hexo-submit-urls-to-search-engine#4]
尝试向谷歌推送，结果失败了，错误代码：
```
FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: connect ETIMEDOUT 172.217.27.138:443                                    
    at ClientRequest.<anonymous> (E:\Hexo\node_modules\gaxios\node_modules\node-fetch\lib\index.js:1455:11)                                               
    at ClientRequest.emit (events.js:315:20)                                 
    at TLSSocket.socketErrorListener (_http_client.js:426:9)                 
    at TLSSocket.emit (events.js:315:20)                                     
    at emitErrorNT (internal/streams/destroy.js:92:8)                        
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)                
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {   
  type: 'system',                                                            
  errno: 'ETIMEDOUT',                                                        
  code: 'ETIMEDOUT',                                                         
  config: {                                                                  
    method: 'POST',                                                          
    url: 'https://www.googleapis.com/oauth2/v4/token',                       
    data: {                                                                  
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',             
      assertion: 'eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJjaHJvbWUtc2VvQHJ1Z2dlZC1udWNsZXVzLTI4MjkwOC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInNjb3BlIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9pbmRleGluZyIsImF1ZCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92NC90b2tlbiIsImV4cCI6MTU5NDM3NDgxOCwiaWF0IjoxNTk0MzcxMjE4LCJzdWIiOm51bGx9.Ff-I2TpeNGTN7AXKVPo3QdlKzucPF6shltHIRsp6nxOmXfwFIB_NJBV2PatI59KKZuQlQjyqri02nmbnZcu2axoLaJB86msFcJw2ZwX9XxhDiv_KVsbqLRQjzYGI_fv8yqmegbiTapF6ZKLTrw1rCr3_KMW0Kp1UdiF1AydeZbgWpcCoumGr8s3bvx-2RkHtsqpis27Phuqbun3ePOJ4mgj87ozyu5qgN8mn5QX3bFu6dm-4NzrpZxCF-KbbmA0QoqjELlGJab2X6g9LbiAmY3lb4khHTTHLViKPcCjzCPO4bjJV8iO0-2aVcdJ3ZR3M4-nJKM7TSRCX5ynHgmvT4A'                          
    },                                                                       
    headers: { 'Content-Type': 'application/json', Accept: 'application/json' },                                                                          
    responseType: 'json',                                                    
    params: [Object: null prototype] {},                                     
    paramsSerializer: [Function: paramsSerializer],                          
    body: '{"grant_type":"urn:ietf:params:oauth:grant-type:jwt-bearer","assertion":"eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJjaHJvbWUtc2VvQHJ1Z2dlZC1udWNsZXVzLTI4MjkwOC5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsInNjb3BlIjoiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9pbmRleGluZyIsImF1ZCI6Imh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92NC90b2tlbiIsImV4cCI6MTU5NDM3NDgxOCwiaWF0IjoxNTk0MzcxMjE4LCJzdWIiOm51bGx9.Ff-I2TpeNGTN7AXKVPo3QdlKzucPF6shltHIRsp6nxOmXfwFIB_NJBV2PatI59KKZuQlQjyqri02nmbnZcu2axoLaJB86msFcJw2ZwX9XxhDiv_KVsbqLRQjzYGI_fv8yqmegbiTapF6ZKLTrw1rCr3_KMW0Kp1UdiF1AydeZbgWpcCoumGr8s3bvx-2RkHtsqpis27Phuqbun3ePOJ4mgj87ozyu5qgN8mn5QX3bFu6dm-4NzrpZxCF-KbbmA0QoqjELlGJab2X6g9LbiAmY3lb4khHTTHLViKPcCjzCPO4bjJV8iO0-2aVcdJ3ZR3M4-nJKM7TSRCX5ynHgmvT4A"}',                                  
    validateStatus: [Function: validateStatus]                               
  }                                                                          
}                                                                                                                               
```
错误截图：
![1](https://user-images.githubusercontent.com/49554285/87136675-69111480-c2ce-11ea-80ff-6c6cd27f1448.png)

**Comment by cjh0613** [comment]
请问科学上网方式？

**Comment by suyin-long** [comment]
> 请问科学上网方式？

代理模式：全局模式
代理规则：绕过局域网和大陆

**Comment by cjh0613** [comment]
问题应该出在底层，可能是程序运行临时问题如网络等。请再多试试。我短时间内无法解决此问题。

**Comment by purplemysticx** [comment]
可以通过在github上设置github action的方式, 由job去部署

**Comment by cjh0613** [comment]
发布了新版 V2.1.0 ，应该可以在中国内地使用谷歌推送了。支持使用系统 http 代理向谷歌提交网址。以配合大多数科学上网软件。需要修改 hexo_submit_urls_to_search_engine: google_proxy  配置项。

https://github.com/cjh0613/hexo-submit-urls-to-search-engine/releases/tag/V2.1.0

文档-插件升级： https://cjh0613.com/20200603HexoSubmitUrlsToSearchEngine.html#%E6%8F%92%E4%BB%B6%E5%8D%87%E7%BA%A7
